version: '3'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    volumes:
      - $PWD/cloudsql:/cloudsql
      - $PWD/db-key.json:/config
    command:
      - /cloud_sql_proxy
      - -instances=react-rails-auth:us-central1:scalr=tcp:0.0.0.0:5432
      - -credential_file=/config
    networks:
      - internal_network
      - external_network
  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
     - ./redis:/data
  web:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system
  streaming:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env
    command: yarn start
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    build: https://github.com/usbsnowcrash/docker-tor.git
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    build: https://github.com/usbsnowcrash/docker-privoxy.git
#    command: /opt/sbin/privoxy --no-daemon --user privoxy.privoxy /opt/config
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
